/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/biblia': RouteRecordInfo<'/biblia', '/biblia', Record<never, never>, Record<never, never>>,
    '/biblia-mobile': RouteRecordInfo<'/biblia-mobile', '/biblia-mobile', Record<never, never>, Record<never, never>>,
    '/biblia-mobile-novo': RouteRecordInfo<'/biblia-mobile-novo', '/biblia-mobile-novo', Record<never, never>, Record<never, never>>,
    '/biblia-novo': RouteRecordInfo<'/biblia-novo', '/biblia-novo', Record<never, never>, Record<never, never>>,
  }
}
